---
name: "CI"

"on":
  ## Events: Pushes on Main
  push:
    branches:
      - main
    paths:
      - docs/**/*.*
      - e2e/**/*.*
      - gradle/**/*.*
      - internal/**/*.*
      - java/**/*.*
      - tools/**/*.*
      - "*.bzl"
      - "*.bazel"

jobs:
  dependency-graph:
    name: "Dependency Graph"
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Report: Dependency Graph"
        continue-on-error: true
        uses: advanced-security/maven-dependency-submission-action@c5ad0fd6b977364190852883b46728f25a9617c3 # v3.0.2

  build:
    name: "Build (${{ matrix.label }})"
    uses: ./.github/workflows/module.build.yml
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]
        main: [false]
        label: ["Ubuntu"]
        labs: [false]
        flags: ["--config=linux"]
        testlabel: ["Ubuntu"]
        coverage: [false]
        include:
          # Bazel 6
          - runner: ubuntu-latest
            label: Ubuntu
            labs: false
            main: false
            coverage: false
            flags: --config=linux
            testlabel: Ubuntu
          - runner: macos-latest
            label: macOS
            labs: false
            main: false
            coverage: false
            flags: --config=macos
            testlabel: macOS
#          - runner: windows-2022
#            label: Windows
#            labs: false
#            main: false
#            coverage: false
#            flags: --config=windows
#            testlabel: Windows

    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      label: ${{ matrix.label }}
      labs: ${{ matrix.labs }}
      main: ${{ matrix.main }}
      flags: ${{ matrix.flags }}
      coverage: ${{ matrix.coverage }}
